services:
  - type: web
    name: proteinsynergydock-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements-api.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: REDIS_URL
        fromService:
          type: redis
          name: proteinsynergydock-redis
          property: connectionString

  - type: redis
    name: proteinsynergydock-redis
    region: oregon
    ipAllowList: []
    plan: free
